import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import NavBar from '@/components/NavBar'
import PageTransition from '@/components/PageTransition'
import PreLoading from '@/components/PreLoading'
import SocialMedia from '@/components/SocialMedia'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { forwardRef } from 'react'

type IndexPageProps = {}
type IndexPageRef = React.ForwardedRef<HTMLDivElement>
function ContactPage(props: IndexPageProps, ref: IndexPageRef) {
  return (
    <>
      <NavBar />
      <PageTransition ref={ref}>
        <Head>
          <title>Ayoub Boudra</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="w-full ">
          {/* <PreLoading /> */}

          <div className="page absolute ">
            {/* <div className='navbar '>
                  
                  
              </div> */}
            <div className="body mt-16" id="home">
              <div className="mb-24">
                <Contact />
              </div>
            </div>
            <div className="">
              <Footer />
            </div>
          </div>
        </main>
      </PageTransition>
    </>
  )
}

export default forwardRef(ContactPage)
