import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavBar from '@/components/NavBar'
import HomePage from '@/components/Home'
import SocialMedia from '@/components/SocialMedia'
import Footer from '@/components/Footer'
import About from '@/components/About'
import Contact from '@/components/Contact'
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ayoub Boudra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full '>
          <div className='page '>
                <div className='navbar '>
                    <NavBar />
                    <div className='hidden drop-shadow-xl lg:block socialmedia-links fixed top-80 lg:w-12 lg:h-56  bg-black rounded-r-xl'>
                      <SocialMedia blocStyle='icons w-full flex-row flex lg:flex-col text-3xl gap-4 my-4 justify-center items-center text-white '/>
                    </div>
                    
                </div>
                <div className='body mt-16' id='home'>
                    <div>
                        <HomePage />
                    </div>
                    {/* <div>
                        <About />
                    </div>
                    <div>
                        <Projects />
                    </div>
                    <div>
                        <Skills />
                    </div> */}
                    <div className='' >
                        <Contact />
                    </div>
                </div>
                <div className='footer w-full  bg-black'>
                    <Footer />
                </div>
          </div>
          
      </main>
    </>
  )
}
