import Footer from '@/components/Footer'
import NavBar from '@/components/NavBar'
import SocialMedia from '@/components/SocialMedia'
import Head from 'next/head'
import React from 'react'

function skills() {
  return (
    <>
        <Head>
      <title>Ayoub Boudra</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className='w-full '>

        {/* <PreLoading /> */}

        <div className='page '>
              <div className='navbar '>
                  <NavBar />
                  <div className='hidden drop-shadow-xl lg:block socialmedia-links fixed top-80 lg:w-12 lg:h-56  bg-black rounded-r-xl'>
                    <SocialMedia blocStyle='icons w-full flex-row flex lg:flex-col text-3xl gap-4 my-4 justify-center items-center text-white z-50'/>
                  </div>
                  
              </div>
              <div className='body mt-16' id='home'>
                  <div>
                      
                  </div>
            </div>  
            <div className=''>
              <Footer />
            </div>
        </div>
        
    </main>
    </>
  )
}

export default skills